CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" varchar(450) NOT NULL,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" varchar(450) NOT NULL,
    "DisplayName" text,
    "DisplayImage" text,
    "UserName" varchar(256),
    "NormalizedUserName" varchar(256),
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamptz,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" int NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Daily" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(200) NOT NULL,
    "DailyDate" timestamp NOT NULL,
    "Closed" boolean NOT NULL,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Daily" PRIMARY KEY ("Id")
);

CREATE TABLE "Departments" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(200) NOT NULL,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" varchar(450) NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" varchar(450) NOT NULL,
    "ProviderKey" varchar(450) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" varchar(450) NOT NULL,
    "RoleId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" varchar(450) NOT NULL,
    "LoginProvider" varchar(450) NOT NULL,
    "Name" varchar(450) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Form" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DailyId" int,
    "Index" int,
    "Description" text,
    "Name" text,
    "CreatedBy" varchar(450),
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Form" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Form_AspNetUsers_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_Form_Daily_DailyId" FOREIGN KEY ("DailyId") REFERENCES "Daily" ("Id")
);

CREATE TABLE "Employees" (
    "Id" varchar(14) NOT NULL,
    "TegaraCode" int,
    "TabCode" int,
    "Name" text NOT NULL,
    "Collage" text,
    "Section" varchar(25),
    "Email" varchar(250),
    "DepartmentId" int,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id")
);

CREATE TABLE "FormRefernce" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FormId" int NOT NULL,
    "ReferencePath" varchar(250),
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_FormRefernce" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FormRefernce_Form_FormId" FOREIGN KEY ("FormId") REFERENCES "Form" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmployeeBank" (
    "EmployeeId" varchar(14) NOT NULL,
    "BankName" text,
    "BranchName" text,
    "AccountNumber" text,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_EmployeeBank" PRIMARY KEY ("EmployeeId"),
    CONSTRAINT "FK_EmployeeBank_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmployeeRefernce" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" varchar(14),
    "ReferencePath" text,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_EmployeeRefernce" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeeRefernce_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id")
);

CREATE TABLE "FormDetails" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FormId" int NOT NULL,
    "EmployeeId" varchar(14),
    "Amount" float NOT NULL,
    "OrderNum" int NOT NULL,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_FormDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FormDetails_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id"),
    CONSTRAINT "FK_FormDetails_Form_FormId" FOREIGN KEY ("FormId") REFERENCES "Form" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;

CREATE INDEX "IX_EmployeeRefernce_EmployeeId" ON "EmployeeRefernce" ("EmployeeId");

CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");

CREATE UNIQUE INDEX "IX_Employees_TabCode" ON "Employees" ("TabCode") WHERE "TabCode" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Employees_TegaraCode" ON "Employees" ("TegaraCode") WHERE "TegaraCode" IS NOT NULL;

CREATE INDEX "IX_Form_CreatedBy" ON "Form" ("CreatedBy");

CREATE INDEX "IX_Form_DailyId" ON "Form" ("DailyId");

CREATE INDEX "IX_FormDetails_EmployeeId" ON "FormDetails" ("EmployeeId");

CREATE INDEX "IX_FormDetails_FormId" ON "FormDetails" ("FormId");

CREATE INDEX "IX_FormRefernce_FormId" ON "FormRefernce" ("FormId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240815134033_Init', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Form" DROP CONSTRAINT "FK_Form_Daily_DailyId";

ALTER TABLE "Form" ADD CONSTRAINT "FK_Form_Daily_DailyId" FOREIGN KEY ("DailyId") REFERENCES "Daily" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240819221452_Daily-Relation-fix', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Employees" DROP CONSTRAINT "FK_Employees_Departments_DepartmentId";

ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240819222322_Department-Relation-fix', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "FormDetails" ADD "IsReviewed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "FormDetails" ADD "IsReviewedBy" varchar(100);

ALTER TABLE "FormDetails" ADD "ReviewComments" text;

ALTER TABLE "FormDetails" ADD "ReviewedAt" timestamp;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250815185021_Add-Review-Field', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "DailyReference" (
    "Id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DailyId" int NOT NULL,
    "ReferencePath" text NOT NULL,
    "Description" text,
    "CreatedBy" text,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedBy" text,
    "UpdatedAt" timestamp,
    "DeactivatedBy" text,
    "DeactivatedAt" timestamp,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_DailyReference" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DailyReference_Daily_DailyId" FOREIGN KEY ("DailyId") REFERENCES "Daily" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DailyReference_DailyId" ON "DailyReference" ("DailyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250907211723_Add-DailyReference', '8.0.0');

COMMIT;
