// <auto-generated />
using System;
using Auth.Infrastructure.Sync;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Infrastructure.Migrations.AzureSync
{
    [DbContext(typeof(AzureSyncContext))]
    [Migration("20260919155715_InitialAzureSyncSchema")]
    partial class InitialAzureSyncSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sync")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Sync.ProcessedOperation", b =>
                {
                    b.Property<string>("DatabaseId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntitySyncId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DatabaseId", "ClientOperationId");

                    b.ToTable("ProcessedOperations", "sync");
                });

            modelBuilder.Entity("Core.Models.Sync.ServerChangeFeed", b =>
                {
                    b.Property<long>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeedId"));

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("EntitySyncId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OriginDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("FeedId");

                    b.HasIndex("DatabaseId", "ServerVersion")
                        .HasDatabaseName("IX_ServerChangeFeed_Pull");

                    b.ToTable("ServerChangeFeed", "sync");
                });

            modelBuilder.Entity("Core.Models.Sync.ServerState", b =>
                {
                    b.Property<string>("DatabaseId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("CurrentVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DatabaseId");

                    b.ToTable("ServerState", "sync");
                });

            modelBuilder.Entity("Core.Models.Sync.ServerTombstone", b =>
                {
                    b.Property<string>("DatabaseId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EntitySyncId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NaturalKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint");

                    b.HasKey("DatabaseId", "EntityType", "EntitySyncId");

                    b.HasIndex("DatabaseId", "ServerVersion")
                        .HasDatabaseName("IX_Tombstones_Pull");

                    b.ToTable("Tombstones", "sync");
                });
#pragma warning restore 612, 618
        }
    }
}
