// <auto-generated />
using System;
using Auth.Infrastructure.Sync;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Infrastructure.Migrations.LocalSync
{
    [DbContext(typeof(LocalSyncContext))]
    partial class LocalSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sync")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Sync.LocalBootstrapManifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureServerSource")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BootstrapTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("IdentityCheckJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWriteAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("MigrationHistoryHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableCheckJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetLocalEngine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BootstrapManifest", "sync");
                });

            modelBuilder.Entity("Core.Models.Sync.LocalOutbox", b =>
                {
                    b.Property<Guid>("ClientOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("EntitySyncId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientOperationId");

                    b.HasIndex("DatabaseId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_LocalOutbox_Queue");

                    b.ToTable("LocalOutbox", "sync");
                });

            modelBuilder.Entity("Core.Models.Sync.LocalState", b =>
                {
                    b.Property<string>("DatabaseId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ActiveLeaseToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("LastServerVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSuccessfulPullUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSuccessfulPushUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DatabaseId");

                    b.ToTable("LocalState", "sync");
                });
#pragma warning restore 612, 618
        }
    }
}
